#databases in postgresql

common: &common
  adapter: postgresql
  encoding: utf8
  username: rnaud
  password: melchi
  
development:
  <<: *common
  database: whatever_dev

test:
  <<: *common
  database: whatever_test

production:
  <<: *common
  database: whatever

